openapi: 3.2.0
info:
  title: Data Bridge Jobs API
  description: Endpoints for Data Bridge.
  version: 2022-09
servers:
- url: https://{host}/databridge
  description: Intelligent Risk Platform
  variables:
    host:
      enum:
      - api-euw1.rms.com
      - api-use1.rms.com
      default: api-euw1.rms.com
      description: 'Data center that hosts the tenant instance: api-euw1.rms.com or api-use1.rms.com.'
security:
- RMS_Auth: []
tags:
- name: Jobs
paths:
  /v1/Jobs/{jobId}:
    get:
      tags:
      - Jobs
      summary: Get job status
      operationId: getjobstatus
      parameters:
      - name: jobId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK. All went well.
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
        '400':
          description: Bad Request. Some of the provided parameters were not valid.
        '410':
          description: Not found. The entity you are trying to interact with does not exist.
        '500':
          description: Internal Server Error. If the problem persists you may want to contact the Administrator.
  /v1/Jobs/{jobId}/details:
    get:
      tags:
      - Jobs
      summary: Get job details
      operationId: getjobdetails
      parameters:
      - name: jobId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK. All went well.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/RMS.BackgroundJobs.JobDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/RMS.BackgroundJobs.JobDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/RMS.BackgroundJobs.JobDetails'
        '400':
          description: Bad Request. Some of the provided parameters were not valid.
        '410':
          description: Not found. The entity you are trying to interact with does not exist.
        '500':
          description: Internal Server Error. If the problem persists you may want to contact the Administrator.
components:
  schemas:
    RMS.BackgroundJobs.JobDetails:
      type: object
      properties:
        error:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    RMS_Auth:
      type: apiKey
      name: Authorization
      in: header
      description: An API key is a token that enables a client application to make requests to tenant applications running on Intelligent Risk Platform.
      x-default: XXXXXXXXXX
x-readme:
  explorer-enabled: false
  samples-languages:
  - curl
  - java
  - csharp
  - node
  - python
  proxy-enabled: true
  samples-enabled: true
